import fs from 'fs';
import solc from 'solc';

const sourceCode = fs.readFileSync('contracts/CrossBorderPayment.sol', 'utf8');

const input = {
    language: 'Solidity',
    sources: {
        'CrossBorderPayment.sol': {
            content: sourceCode
        }
    },
    settings: {
        viaIR: true,          // ← fixes "Stack too deep" with complex functions
        optimizer: {
            enabled: true,
            runs: 200
        },
        outputSelection: {
            '*': {
                '*': ['abi', 'evm.bytecode']
            }
        }
    }
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

if (output.errors) {
    output.errors.forEach(err => console.error(err.formattedMessage));
    if (output.errors.some(e => e.severity === 'error')) process.exit(1);
}

const contract = output.contracts['CrossBorderPayment.sol']['CrossBorderPayment'];
const bytecode = '0x' + contract.evm.bytecode.object;
const abi = contract.abi;

// Preserve SUPPORTED_TOKENS and ERC20_ABI — these are NOT generated by solc
const configContent = `/**
 * Smart Contract Configuration
 *
 * Deploy the contract directly from the app UI using MetaMask.
 * No terminal commands or private key needed.
 *
 * CONTRACT_ADDRESS is auto-saved to localStorage after deployment.
 */

export let CONTRACT_ADDRESS = '';

// Testnet (Sepolia) Supported Tokens
export const SUPPORTED_TOKENS = {
    ETH:  "0x0000000000000000000000000000000000000000",
    USDC: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238", // Official USDC Sepolia
    USDT: "0xaA8E23Fb1079EA71e0a56F48a2aA51851D8433D0",
    DAI:  "0x68194a729C2450ad26072b3D33ADaCbcef39D574"
};

// Minimal standard ABI for token approval and transfers
export const ERC20_ABI = [
    "function approve(address spender, uint256 amount) external returns (bool)",
    "function transferFrom(address sender, address recipient, uint256 amount) external returns (bool)",
    "function transfer(address recipient, uint256 amount) external returns (bool)",
    "function balanceOf(address account) external view returns (uint256)",
    "function decimals() external view returns (uint8)",
    "function symbol() external view returns (string)"
];

// Compiled bytecode from local solc script (Solidity 0.8.20, viaIR optimizer)
export const CONTRACT_BYTECODE = '${bytecode}';

export const CONTRACT_ABI = ${JSON.stringify(abi, null, 4)};
`;

fs.writeFileSync('config.js', configContent);
console.log('✅ Successfully updated config.js with new compiled Bytecode and ABI!');
console.log(`   Bytecode size: ${bytecode.length} chars`);
console.log(`   ABI entries:   ${abi.length}`);
